create components and tables dinamic
Neyver/Battleship-vuejs pull request #2
Opened 2018-08-02 19:38 UTC by Neyver

create components and tables dinamic

2018-08-02 20:24 UTC, pabloorellana requested changes

2018-08-02 20:24 UTC, pabloorellana commented on src/components/Battleship.vue
> +        tableBattle.innerHTML = codigoHTML;
why do you manipulate HTML like this in the component when vuejs has built-in directives to deal with collections? instead of this complex method you could do something like this in your template:
```html
<table class = "table-result" border="1">
  <tbody>
    <tr v-for="row in rows">
      <td v-for="column in columns"></td>
    </tr>
  </tbody>
</table>
```

2018-08-02 20:24 UTC, pabloorellana commented on src/components/Battleship.vue
> +        let codigoHTML='<table class = "table-result" border=\'1\'><tbody>';
do not mix english and spanish in your code

2018-08-02 20:24 UTC, pabloorellana commented on src/components/Battleship.vue
> +    let tableBattle = document.getElementById('table-battle');
bad indentation

2018-08-02 20:24 UTC, pabloorellana commented on src/components/Battleship.vue
> +    EventBus.$on('send-values', (col,row) => {
1. event names should be descriptive, find a better one like "rows-change", "columns-change", "size-change", etc
2. as I know you can only send one value when emitting an event

2018-08-02 20:24 UTC, pabloorellana commented on src/components/Menu.vue
> +      <button type="button" name="button" @click= RecoverData()>Create</button>
should be:
```javascript
@click="recoverData"
```

2018-08-02 20:24 UTC, pabloorellana commented on src/components/Menu.vue
> +	        var numColumnas=parseInt(document.getElementById('column').value);
again, use the library frameworks instead of DOM manipulation, you should use v-model in the template instead of this

2018-08-02 20:24 UTC, pabloorellana commented on src/components/Menu.vue
> +		RecoverData() {
method names should be in cammelCase

2018-08-02 20:24 UTC, pabloorellana commented on src/components/MenuContent.vue
> +	import {EventBus} from '@/services/event-bus';
1. bad indentation
2. unused EventBus

2018-08-02 20:24 UTC, pabloorellana commented on src/components/MenuContent.vue
> +      <input type="text" class="imput" value="" id="column">
should be "input"

2018-08-02 20:24 UTC, pabloorellana commented on src/components/MenuContent.vue
> +   <div class="menuContent">
should be in kebbab case

2018-08-02 20:24 UTC, pabloorellana commented on src/router/index.js
> +//import Battleship from './components/Battleship.vue';
remove commented code

2018-08-07 16:24 UTC, pabloorellana approved these changes

2018-08-07 16:25 UTC, merged

2018-08-07 21:42 UTC, Neyver commented on src/components/Battleship.vue
> +        tableBattle.innerHTML = codigoHTML;
changed by 
<table id="table-battle">
          <tr v-for="row in rows">
            <td v-for="col in cols"></td>
          </tr>      
        </table>

2018-08-07 21:42 UTC, Neyver commented on src/components/Battleship.vue
> +        let codigoHTML='<table class = "table-result" border=\'1\'><tbody>';
removed codigoHTML

2018-08-07 21:42 UTC, Neyver commented on src/components/Battleship.vue
> +    let tableBattle = document.getElementById('table-battle');
removed for not being of vue

2018-08-07 21:42 UTC, Neyver commented on src/components/Battleship.vue
> +    EventBus.$on('send-values', (col,row) => {
send-values by size-change

2018-08-07 21:42 UTC, Neyver commented on src/components/Menu.vue
> +      <button type="button" name="button" @click= RecoverData()>Create</button>
changed by v-on:click = "recoverData"

2018-08-07 21:42 UTC, Neyver commented on src/components/Menu.vue
> +	        var numColumnas=parseInt(document.getElementById('column').value);
removed for not being of vue

2018-08-07 21:43 UTC, Neyver commented on src/components/Menu.vue
> +		RecoverData() {
changed by recoverData

2018-08-07 21:43 UTC, Neyver commented on src/components/MenuContent.vue
> +	import {EventBus} from '@/services/event-bus';
Eliminated for not using

2018-08-07 21:43 UTC, Neyver commented on src/components/MenuContent.vue
> +      <input type="text" class="imput" value="" id="column">
it was necessary was erased

2018-08-07 21:43 UTC, Neyver commented on src/components/MenuContent.vue
> +   <div class="menuContent">
corrected nemu-Content

2018-08-07 21:43 UTC, Neyver commented on src/router/index.js
> +//import Battleship from './components/Battleship.vue';
removed comments that do not work